version: "3.8"

services:
    api:
        ports:
        -   "8080:8080"
        build: .
    db:
        image: mysql
        ports: 
        -   "3306:3306"
        environment: 
        - MYSQL_ROOT_PASSWORD=tiukusql
        - MYSQL_USER=testiuser
        - MYSQL_PASSWORD=testipassword
        - MYSQL_DATABASE=tiukuDB