version: "3.8"

services:
    api:
        container_name: api
        ports:
        - "8080:8080"
        depends_on: 
            - "db"
        working_dir: /tiuku
        volumes:
            - /c/Oamk/Oppari/tiuku:/tiuku
        build: .
        command: go run main.go
    
    db:
        container_name: db
        image: mysql:8
        ports: 
        -   "3306:3306"
        environment: 
        - MYSQL_ROOT_PASSWORD=tiukusql
        - MYSQL_USER=testiuser
        - MYSQL_PASSWORD=testipassword
        - MYSQL_DATABASE=tiukuDB
        volumes:
        - /c/Oamk/Oppari/tiuku-mysql-data:/var/lib/mysql
            
volumes:
    tiuku-mysql-data:
    tiuku: