openapi: 3.0.0
info:
  title: StudentAPI
  description: API for Students to acccess the Tiuku system.
  contact:
    name: Asko Mattila
    email: asko.mattila@gmail.com
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /segments:
    get:
      summary: Get list of active segments of Courses
      description: Get list of your active segments
      operationId: get-user-segments
      responses:
        "200":
          description: OK
    post:
      tags: []
      summary: Add new Segment to CourseList
      description: Add segment to your list
      operationId: post-user-segments
      responses:
        "200":
          description: OK
  /segments/{segment}:
    get:
      summary: Get Session data with ResourceID
      description: Get data from specific Session
      operationId: get-user-segments-ResourceID
      parameters:
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    post:
      summary: Add or start new session to {segment} table.
      description: Add or start session, to {segment} table.
      operationId: post-segments-segment
      parameters:
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /segment/{segment}/settings:
    get:
      summary: Get current settings
      description: Settings for the Segment(?)
      operationId: get-user-segment-settings
      parameters:
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    patch:
      summary: Change settings for the {segment}
      description: Change settings for the {segment}, not sure what that actually
        means.
      operationId: patch-segment-segment-settings
      parameters:
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /courses/{course}/segments/{segment}:
    get:
      summary: Get available courses
      description: Are you enrolled on this segment? True / False
      operationId: get-courses-course-segments-segment
      parameters:
      - name: course
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    post:
      summary: Join segment of the course
      description: Join the {segment} of the {course}
      operationId: post-courses-course-segments-segment
      parameters:
      - name: course
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    delete:
      summary: Leave segment of the course.
      description: Remove yourself from the {segment}
      operationId: delete-courses-course-segments-segment
      parameters:
      - name: course
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /courses:
    get:
      summary: Get list of activel available courses
      description: Get list of available Courses
      operationId: get-courses
      responses:
        "200":
          description: OK
  /courses/{course}/segments/{segment}/categories:
    get:
      description: Get used categories and rules for {segment}
      operationId: get-courses-course-segments-segment-categories
      parameters:
      - name: course
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /segments/{segment}/{session}:
    get:
      summary: Get specific Session from Segment
      description: Get data of specific Session from Segment
      operationId: get-segments-segment-session
      parameters:
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: session
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    put:
      summary: Replace {session} with new data
      description: Replace {session}.
      operationId: put-segments-segment-session
      parameters:
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: session
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    delete:
      summary: Remove {session}
      description: Remove specific {session} from {segment}
      operationId: delete-segments-segment-session
      parameters:
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: session
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    patch:
      summary: Stop session by inserting Stop time
      description: 'Stop {sessions}, inserts, '
      operationId: patch-segments-segment-session
      parameters:
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: session
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /courses/{course}/segments:
    get:
      summary: Get list of Segments on the course
      description: Get {segments} that the {course} has.
      operationId: get-courses-course-segments
      parameters:
      - name: course
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /segments/{segment}/settings/{setting}:
    get:
      tags: []
      summary: Get value of {setting}
      description: Get value of Specific {setting}
      operationId: get-segments-segment-settings-setting
      parameters:
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: setting
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
    patch:
      summary: Update {setting} for {segment}
      description: Update {Setting} for {Segment}
      operationId: patch-segments-segment-settings-setting
      parameters:
      - name: segment
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: setting
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
components:
  schemas:
    NewSession:
      title: NewSession
      type: object
      properties:
        id:
          type: string
        ? ""
        : type: string
  securitySchemes: {}
